import React, { useState } from 'react'
import { Github, Send, CheckCircle, AlertCircle, ExternalLink } from 'lucide-react'
import { DraggableModal } from './DraggableModal'
import { useCanvasStore } from '../../stores/canvasStore'
import { toast } from '../Toast'

interface GitHubPRModalProps { onClose: () => void }

type Step = 'config' | 'pushing' | 'done' | 'error'

export function GitHubPRModal({ onClose }: GitHubPRModalProps) {
  const { generatedCode, project } = useCanvasStore()

  const [token,    setToken]    = useState(() => localStorage.getItem('bb-gh-token') ?? '')
  const [repo,     setRepo]     = useState(() => localStorage.getItem('bb-gh-repo') ?? '')
  const [branch,   setBranch]   = useState('block-builder/generated')
  const [prTitle,  setPrTitle]  = useState(() => 'feat: ' + (project.name ?? 'Generated code') + ' from Block Builder')
  const [step,     setStep]     = useState<Step>('config')
  const [prUrl,    setPrUrl]    = useState('')
  const [error,    setError]    = useState('')
  const [log,      setLog]      = useState<string[]>([])

  const addLog = (msg: string) => setLog(prev => [...prev, msg])

  const handlePush = async () => {
    if (!token.trim() || !repo.trim()) {
      toast.error('請填入 Token 和 Repo')
      return
    }
    if (!generatedCode?.files.length) {
      toast.error('請先生成代碼')
      return
    }

    localStorage.setItem('bb-gh-token', token)
    localStorage.setItem('bb-gh-repo', repo)

    setStep('pushing')
    setLog([])

    const headers = {
      'Authorization': 'token ' + token,
      'Accept': 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
    }
    const apiBase = 'https://api.github.com/repos/' + repo

    try {
      // 1. Get default branch SHA
      addLog('🔍 取得 repo 資訊...')
      const repoRes = await fetch(apiBase, { headers })
      if (!repoRes.ok) throw new Error('無法存取 repo，請確認 token 和 repo 名稱正確')
      const repoData = await repoRes.json()
      const defaultBranch: string = repoData.default_branch ?? 'main'

      // 2. Get base SHA
      addLog('📌 取得 ' + defaultBranch + ' 最新 commit...')
      const refRes = await fetch(apiBase + '/git/ref/heads/' + defaultBranch, { headers })
      if (!refRes.ok) throw new Error('無法取得 ' + defaultBranch + ' branch')
      const refData = await refRes.json()
      const baseSha: string = refData.object.sha

      // 3. Create blobs for each file
      addLog('📦 上傳 ' + generatedCode.files.length + ' 個檔案...')
      const treeItems: any[] = []
      let uploaded = 0

      for (const file of generatedCode.files) {
        const blobRes = await fetch(apiBase + '/git/blobs', {
          method: 'POST',
          headers,
          body: JSON.stringify({
            content: btoa(unescape(encodeURIComponent(file.content))),
            encoding: 'base64',
          }),
        })
        if (!blobRes.ok) throw new Error('上傳 ' + file.path + ' 失敗')
        const blob = await blobRes.json()
        treeItems.push({ path: file.path, mode: '100644', type: 'blob', sha: blob.sha })
        uploaded++
        if (uploaded % 5 === 0) addLog('  已上傳 ' + uploaded + '/' + generatedCode.files.length)
      }

      // 4. Create tree
      addLog('🌲 建立 Git tree...')
      const treeRes = await fetch(apiBase + '/git/trees', {
        method: 'POST',
        headers,
        body: JSON.stringify({ base_tree: baseSha, tree: treeItems }),
      })
      if (!treeRes.ok) throw new Error('建立 tree 失敗')
      const treeData = await treeRes.json()

      // 5. Create commit
      addLog('💾 建立 commit...')
      const commitRes = await fetch(apiBase + '/git/commits', {
        method: 'POST',
        headers,
        body: JSON.stringify({
          message: 'feat: ' + project.name + ' — generated by Block Builder\n\nGenerated files:\n' +
            generatedCode.files.map(f => '- ' + f.path).join('\n'),
          tree: treeData.sha,
          parents: [baseSha],
        }),
      })
      if (!commitRes.ok) throw new Error('建立 commit 失敗')
      const commitData = await commitRes.json()

      // 6. Create or update branch
      addLog('🌿 建立分支 ' + branch + '...')
      const branchRes = await fetch(apiBase + '/git/refs', {
        method: 'POST',
        headers,
        body: JSON.stringify({ ref: 'refs/heads/' + branch, sha: commitData.sha }),
      })

      if (!branchRes.ok) {
        // Branch exists, update it
        await fetch(apiBase + '/git/refs/heads/' + branch, {
          method: 'PATCH',
          headers,
          body: JSON.stringify({ sha: commitData.sha, force: true }),
        })
        addLog('  分支已更新')
      } else {
        addLog('  分支已建立')
      }

      // 7. Create PR
      addLog('🚀 建立 Pull Request...')
      const prBody = [
        '## Block Builder — 自動生成代碼',
        '',
        '**專案：** ' + project.name,
        '**生成時間：** ' + new Date().toLocaleString('zh-TW'),
        '',
        '### 生成的檔案',
        generatedCode.files.map(f => '- `' + f.path + '`').join('\n'),
        '',
        '---',
        '*此 PR 由 [Block Builder](https://github.com) 自動生成*',
      ].join('\n')

      const prRes = await fetch(apiBase + '/pulls', {
        method: 'POST',
        headers,
        body: JSON.stringify({
          title: prTitle,
          body: prBody,
          head: branch,
          base: defaultBranch,
        }),
      })
      if (!prRes.ok) throw new Error('建立 PR 失敗')
      const prData = await prRes.json()

      setPrUrl(prData.html_url)
      setStep('done')
      addLog('✅ PR 建立成功！')
      toast.success('GitHub PR 建立成功！')

    } catch (e: any) {
      setError(e.message ?? '未知錯誤')
      setStep('error')
      addLog('❌ ' + (e.message ?? '未知錯誤'))
    }
  }

  const footer = step === 'config' ? (
    <div className="flex gap-2">
      <button onClick={onClose} className="px-4 py-2 text-sm text-gray-500 hover:text-gray-700 border border-gray-200 rounded-xl transition-colors flex-1">
        取消
      </button>
      <button
        onClick={handlePush}
        disabled={!token || !repo || !generatedCode}
        className="flex items-center justify-center gap-2 px-4 py-2 text-sm font-medium bg-gray-900 text-white rounded-xl hover:bg-gray-700 disabled:opacity-40 transition-colors flex-1"
      >
        <Github size={14} /> 推送並建立 PR
      </button>
    </div>
  ) : step === 'done' ? (
    <div className="flex gap-2">
      <button onClick={onClose} className="px-4 py-2 text-sm border border-gray-200 rounded-xl flex-1">關閉</button>
      <a href={prUrl} target="_blank" rel="noreferrer"
        className="flex items-center justify-center gap-2 px-4 py-2 text-sm font-medium bg-gray-900 text-white rounded-xl hover:bg-gray-700 flex-1">
        查看 PR <ExternalLink size={12} />
      </a>
    </div>
  ) : null

  return (
    <DraggableModal
      title="推送到 GitHub"
      subtitle="自動建立 Pull Request"
      icon={<Github size={14} />}
      onClose={onClose}
      footer={footer ?? undefined}
      width={500}
      maxHeight="85vh"
    >
      <div className="p-5 space-y-4">

        {step === 'config' && (
          <>
            {/* Token */}
            <div>
              <label className="text-xs font-medium text-gray-500 uppercase tracking-wide block mb-1.5">
                GitHub Personal Access Token
              </label>
              <input
                type="password"
                value={token}
                onChange={e => setToken(e.target.value)}
                placeholder="ghp_xxxxxxxxxxxx"
                className="w-full px-3 py-2 text-xs font-mono border border-gray-200 rounded-xl outline-none focus:border-blue-400"
              />
              <div className="flex items-center justify-between mt-1">
                <p className="text-xs text-gray-400">需要 repo 和 workflow 權限</p>
                <a href="https://github.com/settings/tokens/new?scopes=repo" target="_blank" rel="noreferrer"
                  className="text-xs text-blue-500 hover:text-blue-700 flex items-center gap-1">
                  建立 Token <ExternalLink size={10} />
                </a>
              </div>
            </div>

            {/* Repo */}
            <div>
              <label className="text-xs font-medium text-gray-500 uppercase tracking-wide block mb-1.5">
                Repository
              </label>
              <input
                type="text"
                value={repo}
                onChange={e => setRepo(e.target.value)}
                placeholder="owner/repo-name"
                className="w-full px-3 py-2 text-xs font-mono border border-gray-200 rounded-xl outline-none focus:border-blue-400"
              />
            </div>

            {/* Branch */}
            <div>
              <label className="text-xs font-medium text-gray-500 uppercase tracking-wide block mb-1.5">
                分支名稱
              </label>
              <input
                type="text"
                value={branch}
                onChange={e => setBranch(e.target.value)}
                className="w-full px-3 py-2 text-xs font-mono border border-gray-200 rounded-xl outline-none focus:border-blue-400"
              />
            </div>

            {/* PR Title */}
            <div>
              <label className="text-xs font-medium text-gray-500 uppercase tracking-wide block mb-1.5">
                PR 標題
              </label>
              <input
                type="text"
                value={prTitle}
                onChange={e => setPrTitle(e.target.value)}
                className="w-full px-3 py-2 text-sm border border-gray-200 rounded-xl outline-none focus:border-blue-400"
              />
            </div>

            {/* Files summary */}
            {generatedCode && (
              <div className="bg-gray-50 rounded-xl p-3 border border-gray-200">
                <p className="text-xs font-medium text-gray-600 mb-1">
                  將推送 {generatedCode.files.length} 個檔案
                </p>
                <div className="flex gap-3 text-xs text-gray-400">
                  {generatedCode.summary.types.length > 0 && <span>{generatedCode.summary.types.length} 型別</span>}
                  {generatedCode.summary.endpoints.length > 0 && <span>{generatedCode.summary.endpoints.length} API</span>}
                  {generatedCode.summary.hooks.length > 0 && <span>{generatedCode.summary.hooks.length} Hooks</span>}
                </div>
              </div>
            )}

            {!generatedCode && (
              <div className="bg-amber-50 border border-amber-200 rounded-xl p-3 text-xs text-amber-700">
                ⚠️ 請先點「▶ 生成代碼」再推送
              </div>
            )}
          </>
        )}

        {/* Log output */}
        {(step === 'pushing' || step === 'done' || step === 'error') && (
          <div>
            {step === 'pushing' && (
              <div className="flex items-center gap-2 mb-3">
                <div className="w-4 h-4 border-2 border-blue-500 border-t-transparent rounded-full animate-spin" />
                <span className="text-sm font-medium text-gray-700">推送中...</span>
              </div>
            )}
            {step === 'done' && (
              <div className="flex items-center gap-2 mb-3">
                <CheckCircle size={16} className="text-green-500" />
                <span className="text-sm font-medium text-green-700">PR 建立成功！</span>
              </div>
            )}
            {step === 'error' && (
              <div className="flex items-center gap-2 mb-3">
                <AlertCircle size={16} className="text-red-500" />
                <span className="text-sm font-medium text-red-700">{error}</span>
              </div>
            )}
            <div className="bg-gray-900 rounded-xl p-3 font-mono text-xs text-gray-300 space-y-1 max-h-48 overflow-y-auto">
              {log.map((line, i) => (
                <div key={i}>{line}</div>
              ))}
            </div>
          </div>
        )}
      </div>
    </DraggableModal>
  )
}
