import type { InterfaceData, ApiEndpointData, DtoData } from '@block-builder/types'

// ─── Python FastAPI ───────────────────────────────────────────────────
export function generatePythonModel(data: InterfaceData): string {
  const tsToPhython = (t: string): string => {
    const map: Record<string, string> = {
      string: 'str', number: 'float', int: 'int', boolean: 'bool',
      Date: 'datetime', any: 'Any', unknown: 'Any',
    }
    const clean = t.replace('[]', '').replace('| null', '').replace('| undefined', '').trim()
    const base = map[clean] ?? clean
    if (t.endsWith('[]')) return 'List[' + base + ']'
    if (t.includes('| null') || t.includes('| undefined')) return 'Optional[' + base + ']'
    return base
  }

  const fields = data.fields.map(f => {
    const pyType = tsToPhython(f.type)
    const optional = f.optional || f.type.includes('| null')
    return '    ' + f.name + ': ' + (optional ? 'Optional[' + pyType.replace('Optional[', '').replace(']', '') + ']' : pyType) +
      (optional ? ' = None' : '')
  }).join('\n')

  return [
    'from pydantic import BaseModel, EmailStr',
    'from typing import Optional, List, Any',
    'from datetime import datetime',
    '',
    '',
    'class ' + data.name + '(BaseModel):',
    '    """' + data.name + ' model — auto-generated by Block Builder"""',
    fields,
    '',
    '    class Config:',
    '        from_attributes = True',
    '',
  ].join('\n')
}

export function generateFastAPIRoute(data: ApiEndpointData): string {
  const method = data.method.toLowerCase()
  const path = data.path.replace(/:(\w+)/g, '{$1}')
  const hasBody = ['post', 'put', 'patch'].includes(method)
  const hasId = data.path.includes(':id')
  const responseType = data.responseType.replace('[]', '')
  const isArray = data.responseType.includes('[]')

  const params: string[] = []
  if (hasId) params.push('item_id: str')
  if (hasBody) params.push('body: ' + (data.bodyType ?? 'dict'))
  if (data.auth) params.push('current_user = Depends(get_current_user)')

  const paramStr = params.length ? ', ' + params.join(', ') : ''
  const returnType = isArray ? 'List[' + responseType + ']' : responseType

  return [
    'from fastapi import APIRouter, Depends, HTTPException',
    'from typing import List',
    '',
    'router = APIRouter()',
    '',
    '',
    '@router.' + method + '("' + path + '"' + (data.auth ? ', dependencies=[Depends(get_current_user)]' : '') + ')',
    'async def ' + pathToFnName(data.path, data.method) + '(db: Session = Depends(get_db)' + paramStr + ') -> ' + returnType + ':',
    '    """' + (data.summary || data.method + ' ' + data.path) + '"""',
    '    # TODO: implement',
    hasId
      ? '    item = db.query(' + responseType + ').filter(' + responseType + '.id == item_id).first()\n    if not item:\n        raise HTTPException(status_code=404, detail="Not found")\n    return item'
      : isArray
      ? '    return db.query(' + responseType + ').all()'
      : '    pass',
  ].join('\n')
}

// ─── Go Gin ───────────────────────────────────────────────────────────
export function generateGoStruct(data: InterfaceData): string {
  const tsToGo = (t: string, name: string): string => {
    const map: Record<string, string> = {
      string: 'string', number: 'float64', int: 'int', boolean: 'bool',
      Date: 'time.Time', any: 'interface{}', unknown: 'interface{}',
    }
    const clean = t.replace('[]', '').replace('| null', '').replace('| undefined', '').trim()
    let base = map[clean] ?? clean
    if (t.endsWith('[]')) base = '[]' + base
    if (t.includes('| null') || t.includes('| undefined')) base = '*' + base
    return base
  }

  const fields = data.fields.map(f => {
    const goType = tsToGo(f.type, f.name)
    const jsonTag = '`json:"' + f.name + (f.optional ? ',omitempty' : '') + '"`'
    const goName = f.name.charAt(0).toUpperCase() + f.name.slice(1)
    return '\t' + goName + ' ' + goType + ' ' + jsonTag
  }).join('\n')

  return [
    'package models',
    '',
    'import "time"',
    '',
    '// ' + data.name + ' — auto-generated by Block Builder',
    'type ' + data.name + ' struct {',
    fields,
    '}',
    '',
  ].join('\n')
}

export function generateGinRoute(data: ApiEndpointData): string {
  const method = data.method.charAt(0) + data.method.slice(1).toLowerCase()
  const path = data.path.replace(/:(\w+)/g, ':$1')
  const hasId = data.path.includes(':id')
  const handlerName = pathToGoFn(data.path, data.method)
  const responseType = data.responseType.replace('[]', '')

  return [
    'package handlers',
    '',
    'import (',
    '\t"net/http"',
    '\t"github.com/gin-gonic/gin"',
    ')',
    '',
    '// ' + handlerName + ' — ' + (data.summary || data.method + ' ' + data.path),
    'func ' + handlerName + '(c *gin.Context) {',
    hasId ? '\tid := c.Param("id")' : '',
    '\t// TODO: implement',
    '\tc.JSON(http.StatusOK, gin.H{"success": true, "data": nil})',
    '}',
    '',
    '// Register routes',
    'func Register' + responseType + 'Routes(r *gin.RouterGroup) {',
    '\tr.' + method + '("' + path + '", ' + handlerName + ')',
    '}',
  ].filter(l => l !== '').join('\n')
}

// ─── Java Spring Boot ─────────────────────────────────────────────────
export function generateJavaEntity(data: InterfaceData): string {
  const tsToJava = (t: string): string => {
    const map: Record<string, string> = {
      string: 'String', number: 'Double', int: 'Integer', boolean: 'Boolean',
      Date: 'LocalDateTime', any: 'Object', unknown: 'Object',
    }
    const clean = t.replace('[]', '').replace('| null', '').replace('| undefined', '').trim()
    const base = map[clean] ?? clean
    if (t.endsWith('[]')) return 'List<' + base + '>'
    return base
  }

  const fields = data.fields.map(f => {
    const javaType = tsToJava(f.type)
    const annotations: string[] = []
    if (f.name === 'id') annotations.push('    @Id\n    @GeneratedValue(strategy = GenerationType.UUID)')
    if (f.name === 'email') annotations.push('    @Column(unique = true)')
    if (f.name === 'createdAt') annotations.push('    @CreationTimestamp')
    if (f.name === 'updatedAt') annotations.push('    @UpdateTimestamp')
    return (annotations.length ? annotations.join('\n') + '\n' : '') +
      '    private ' + javaType + ' ' + f.name + ';'
  }).join('\n\n')

  return [
    'package com.example.model;',
    '',
    'import jakarta.persistence.*;',
    'import lombok.*;',
    'import org.hibernate.annotations.*;',
    'import java.time.LocalDateTime;',
    'import java.util.List;',
    '',
    '/** ' + data.name + ' entity — auto-generated by Block Builder */',
    '@Entity',
    '@Table(name = "' + toSnakeCase(data.name) + '")',
    '@Data',
    '@Builder',
    '@NoArgsConstructor',
    '@AllArgsConstructor',
    'public class ' + data.name + ' {',
    '',
    fields,
    '',
    '}',
  ].join('\n')
}

export function generateSpringController(data: ApiEndpointData): string {
  const method = data.method
  const annotation = {
    GET: '@GetMapping', POST: '@PostMapping',
    PUT: '@PutMapping', PATCH: '@PatchMapping', DELETE: '@DeleteMapping',
  }[method] ?? '@GetMapping'
  const path = data.path.replace(/:(\w+)/g, '{$1}')
  const responseType = data.responseType.replace('[]', '')
  const hasId = data.path.includes(':id')
  const hasBody = ['POST', 'PUT', 'PATCH'].includes(method)

  const params: string[] = []
  if (hasId) params.push('@PathVariable String id')
  if (hasBody) params.push('@RequestBody ' + (data.bodyType ?? responseType + 'DTO') + ' dto')
  const paramStr = params.join(', ')

  return [
    'package com.example.controller;',
    '',
    'import org.springframework.web.bind.annotation.*;',
    'import org.springframework.http.ResponseEntity;',
    'import lombok.RequiredArgsConstructor;',
    'import java.util.List;',
    '',
    '@RestController',
    '@RequestMapping("/api/' + toSnakeCase(responseType) + 's")',
    '@RequiredArgsConstructor',
    'public class ' + responseType + 'Controller {',
    '',
    '    private final ' + responseType + 'Service service;',
    '',
    '    /** ' + (data.summary || method + ' ' + path) + ' */',
    (data.auth ? '    @PreAuthorize("isAuthenticated()")' : ''),
    '    ' + annotation + '("' + (hasId ? '/{id}' : '') + '")',
    '    public ResponseEntity<?> ' + pathToJavaFn(data.path, method) + '(' + paramStr + ') {',
    '        // TODO: implement',
    '        return ResponseEntity.ok(null);',
    '    }',
    '',
    '}',
  ].filter(l => l !== '').join('\n')
}

// ─── Helpers ──────────────────────────────────────────────────────────
function pathToFnName(path: string, method: string): string {
  const parts = path.split('/').filter(p => p && !p.startsWith(':'))
  const resource = parts[parts.length - 1] ?? 'resource'
  const hasId = path.includes(':id')
  const map: Record<string, string> = {
    GET: hasId ? 'get_' + resource : 'list_' + resource,
    POST: 'create_' + resource,
    PUT: 'update_' + resource,
    PATCH: 'patch_' + resource,
    DELETE: 'delete_' + resource,
  }
  return map[method] ?? method.toLowerCase() + '_' + resource
}

function pathToGoFn(path: string, method: string): string {
  const fn = pathToFnName(path, method)
  return fn.split('_').map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('')
}

function pathToJavaFn(path: string, method: string): string {
  const parts = path.split('/').filter(p => p && !p.startsWith(':'))
  const resource = parts[parts.length - 1] ?? 'resource'
  const hasId = path.includes(':id')
  const map: Record<string, string> = {
    GET: hasId ? 'getById' : 'getAll',
    POST: 'create',
    PUT: 'update',
    PATCH: 'patch',
    DELETE: 'delete',
  }
  return (map[method] ?? method.toLowerCase()) + resource.charAt(0).toUpperCase() + resource.slice(1)
}

function toSnakeCase(s: string): string {
  return s.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '')
}
