import type { ApiEndpointData } from '@block-builder/types'
import yaml from 'js-yaml'

interface OpenApiSpec {
  openapi: string
  info: { title: string; version: string; description?: string }
  paths: Record<string, Record<string, unknown>>
  components: {
    securitySchemes?: Record<string, unknown>
    schemas?: Record<string, unknown>
  }
}

export function generateOpenApiSpec(endpoints: ApiEndpointData[]): string {
  const spec: OpenApiSpec = {
    openapi: '3.0.0',
    info: {
      title: 'Generated API',
      version: '1.0.0',
      description: 'Generated by Block Builder',
    },
    paths: {},
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        },
      },
    },
  }

  for (const ep of endpoints) {
    if (!spec.paths[ep.path]) {
      spec.paths[ep.path] = {}
    }

    const method = ep.method.toLowerCase()
    const operation: Record<string, unknown> = {
      summary: ep.summary || `${ep.method} ${ep.path}`,
      tags: ep.tags.length ? ep.tags : ['general'],
      responses: {
        '200': {
          description: 'Success',
          content: {
            'application/json': {
              schema: {
                type: 'object',
                properties: {
                  data: { $ref: `#/components/schemas/${ep.responseType}` },
                  success: { type: 'boolean' },
                },
              },
            },
          },
        },
        '400': { description: 'Bad Request' },
        '401': { description: 'Unauthorized' },
        '500': { description: 'Internal Server Error' },
      },
    }

    if (ep.auth) {
      operation.security = [{ bearerAuth: [] }]
    }

    if (ep.bodyType) {
      operation.requestBody = {
        required: true,
        content: {
          'application/json': {
            schema: { $ref: `#/components/schemas/${ep.bodyType}` },
          },
        },
      }
    }

    if (ep.queryParams?.length) {
      operation.parameters = ep.queryParams.map((p) => ({
        name: p.name,
        in: 'query',
        required: !p.optional,
        schema: { type: p.type.toLowerCase() },
        description: p.description,
      }))
    }

    spec.paths[ep.path][method] = operation
  }

  return yaml.dump(spec, { indent: 2, lineWidth: 120 })
}
