import type { InterfaceData, FieldDef } from '@block-builder/types'

// ─── Type mapping TS → Prisma ─────────────────────────────────────────
function tsToPrismaType(tsType: string): string {
  const clean = tsType.replace('[]', '').replace('| null', '').replace('| undefined', '').trim()
  const map: Record<string, string> = {
    string: 'String',
    number: 'Int',
    float: 'Float',
    boolean: 'Boolean',
    Date: 'DateTime',
    'Date | null': 'DateTime?',
    Buffer: 'Bytes',
    bigint: 'BigInt',
    any: 'Json',
    object: 'Json',
    Record: 'Json',
  }
  return map[clean] ?? clean  // fallback = assume it's a relation model
}

function isRelation(tsType: string): boolean {
  const primitives = ['string', 'number', 'boolean', 'Date', 'Buffer', 'bigint', 'any', 'object', 'float', 'int']
  const clean = tsType.replace('[]', '').replace('| null', '').replace('| undefined', '').trim()
  return !primitives.includes(clean) && /^[A-Z]/.test(clean)
}

function isArray(tsType: string): boolean {
  return tsType.includes('[]')
}

// ─── Single model ─────────────────────────────────────────────────────
export function generatePrismaModel(data: InterfaceData): string {
  const lines: string[] = []

  for (const field of data.fields) {
    const tsType = field.type ?? 'String'
    const optional = field.optional ? '?' : ''

    if (isRelation(tsType)) {
      const modelName = tsType.replace('[]', '').replace('| null', '').trim()
      const isArr = isArray(tsType)
      if (isArr) {
        // one-to-many: opposite side holds FK
        lines.push(`  ${field.name}      ${modelName}[]`)
      } else {
        // many-to-one: this side holds FK
        lines.push(`  ${field.name}      ${modelName}${optional}   @relation(fields: [${field.name}Id], references: [id])`)
        lines.push(`  ${field.name}Id    String${optional}`)
      }
    } else {
      const prismaType = tsToPrismaType(tsType)
      let decorators = ''

      // Auto-detect common field patterns
      if (field.name === 'id') {
        decorators = ' @id @default(uuid())'
      } else if (field.name === 'createdAt') {
        decorators = ' @default(now())'
      } else if (field.name === 'updatedAt') {
        decorators = ' @updatedAt'
      } else if (field.name === 'email') {
        decorators = ' @unique'
      } else if (field.name === 'slug') {
        decorators = ' @unique'
      } else if (field.name === 'order' || field.name === 'sortOrder') {
        decorators = ' @default(0)'
      } else if (field.name === 'isActive' || field.name === 'enabled') {
        decorators = ' @default(true)'
      } else if (field.name === 'deletedAt') {
        decorators = ' // soft delete'
      }

      lines.push(`  ${field.name.padEnd(16)}${prismaType}${optional}${decorators}`)
    }
  }

  return `model ${data.name} {
${lines.join('\n')}

  @@map("${toSnakeCase(data.name)}")
}
`
}

// ─── Full schema file ─────────────────────────────────────────────────
export function generatePrismaSchema(interfaces: InterfaceData[]): string {
  const models = interfaces.map(generatePrismaModel).join('\n')

  return `// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema
// Generated by Block Builder

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

${models}
`
}

// ─── Helpers ──────────────────────────────────────────────────────────
function toSnakeCase(str: string): string {
  return str
    .replace(/([A-Z])/g, '_$1')
    .toLowerCase()
    .replace(/^_/, '')
    .replace(/s$/, '') // simple singularize
    + 's'
}
