import type { InterfaceData, DtoData, EnumData } from '@block-builder/types'

// ─── Interface Generator ─────────────────────────────────────────────




// ─── Field helpers ────────────────────────────────────────────────────
function fieldExample(type: string, name: string): string {
  if (name === 'id') return "'abc-123'"
  if (name === 'email') return "'user@example.com'"
  if (name === 'name') return "'John Doe'"
  if (name === 'password') return "'P@ssword123'"
  if (name.endsWith('At') || name.includes('Date')) return "new Date().toISOString()"
  if (type === 'number' || type === 'int') return '42'
  if (type === 'boolean') return 'true'
  if (type.endsWith('[]')) return '[]'
  return "'example'"
}

export function generateInterface(data: InterfaceData): string {
  const extendsClause = data.extends?.length
    ? ` extends ${data.extends.join(', ')}`
    : ''

  const fields = data.fields
    .map((f) => {
      const optional = f.optional ? '?' : ''
      const comment = f.description ? `  /** ${f.description} */\n` : ''
      return `${comment}  ${f.name}${optional}: ${f.type}`
    })
    .join('\n')

  return `/**\n * ${data.name} entity\n * @description Auto-generated by Block Builder\n */\nexport interface ${data.name}${extendsClause} {\n${fields}\n}\n`
}

// ─── DTO Generator ───────────────────────────────────────────────────
export function generateDto(data: DtoData): string {
  if (data.validator === 'zod') {
    return generateZodDto(data)
  } else if (data.validator === 'class-validator') {
    return generateClassValidatorDto(data)
  } else {
    return generatePlainDto(data)
  }
}

function generateZodDto(data: DtoData): string {
  const fields = data.fields
    .map((f) => {
      const zodType = tsTypeToZod(f.type, f.optional)
      const validation = f.validation?.join('.') ?? ''
      return `  ${f.name}: z.${zodType}${validation ? `.${validation}` : ''}`
    })
    .join(',\n')

  return `import { z } from 'zod'

export const ${data.name}Schema = z.object({\n${fields}\n})

export type ${data.name} = z.infer<typeof ${data.name}Schema>
`
}

function generateClassValidatorDto(data: DtoData): string {
  const imports = new Set(['IsNotEmpty', 'IsOptional'])
  const fields = data.fields.map((f) => {
    const decorators: string[] = []
    if (f.optional) {
      decorators.push('  @IsOptional()')
      imports.add('IsOptional')
    } else {
      decorators.push('  @IsNotEmpty()')
    }
    if (f.type === 'string') {
      decorators.push('  @IsString()')
      imports.add('IsString')
    }
    if (f.type === 'number') {
      decorators.push('  @IsNumber()')
      imports.add('IsNumber')
    }
    if (f.type === 'boolean') {
      decorators.push('  @IsBoolean()')
      imports.add('IsBoolean')
    }
    const optional = f.optional ? '?' : '!'
    return `${decorators.join('\n')}\n  ${f.name}${optional}: ${f.type}`
  })

  return `import { ${[...imports].join(', ')} } from 'class-validator'

export class ${data.name} {\n${fields.join('\n\n')}\n}\n`
}

function generatePlainDto(data: DtoData): string {
  const fields = data.fields
    .map((f) => {
      const optional = f.optional ? '?' : ''
      return `  ${f.name}${optional}: ${f.type}`
    })
    .join('\n')

  return `/**\n * ${data.name} entity\n * @description Auto-generated by Block Builder\n */\nexport interface ${data.name} {\n${fields}\n}\n`
}

// ─── Enum Generator ──────────────────────────────────────────────────
export function generateEnum(data: EnumData): string {
  const members = data.values
    .map((v) => {
      const val =
        data.style === 'string' ? `'${v.value}'` : v.value
      return `  ${v.key} = ${val}`
    })
    .join(',\n')

  return `export enum ${data.name} {\n${members}\n}\n`
}

// ─── Helpers ─────────────────────────────────────────────────────────
function tsTypeToZod(type: string, optional?: boolean): string {
  const baseMap: Record<string, string> = {
    string: 'string()',
    number: 'number()',
    boolean: 'boolean()',
    Date: 'date()',
    'string[]': 'array(z.string())',
    'number[]': 'array(z.number())',
  }
  const base = baseMap[type] ?? 'unknown()'
  return optional ? `${base}.optional()` : base
}

// ─── Zod schema from Interface ────────────────────────────────────────
function tsToZod(type: string, name: string, optional: boolean): string {
  const clean = type.replace('[]', '').replace('| null', '').replace('| undefined', '').trim()
  const map: Record<string, string> = {
    string: 'z.string()', number: 'z.number()', boolean: 'z.boolean()',
    Date: 'z.coerce.date()', any: 'z.any()', unknown: 'z.unknown()',
  }
  let base = map[clean] ?? 'z.string()'

  // Add semantic validators
  if (name === 'email') base = 'z.string().email()'
  if (name === 'url' || name.endsWith('Url')) base = 'z.string().url()'
  if (name === 'password') base = 'z.string().min(8)'
  if (name === 'phone') base = "z.string().regex(/^\\+?[1-9]\\d{1,14}$/)"
  if (name === 'slug') base = "z.string().regex(/^[a-z0-9-]+$/)"
  if (type.endsWith('[]')) base = `z.array(${map[clean] ?? 'z.string()'})`
  if (optional || type.includes('| null') || type.includes('| undefined')) base += '.optional()'
  if (type.includes('| null')) base += '.nullable()'
  return base
}

export function generateZodSchema(data: InterfaceData): string {
  const fields = data.fields.map(f =>
    `  ${f.name}: ${tsToZod(f.type, f.name, f.optional ?? false)}`
  ).join(',\n')

  return `import { z } from 'zod'

/**
 * Zod schema for ${data.name}
 * Auto-generated by Block Builder
 */
export const ${lcFirst(data.name)}Schema = z.object({
${fields}
})

export type ${data.name}Input = z.infer<typeof ${lcFirst(data.name)}Schema>

// Partial schema for updates
export const ${lcFirst(data.name)}UpdateSchema = ${lcFirst(data.name)}Schema.partial()
export type ${data.name}UpdateInput = z.infer<typeof ${lcFirst(data.name)}UpdateSchema>
`
}

function lcFirst(s: string) { return s.charAt(0).toLowerCase() + s.slice(1) }
