import type { BlockDefinition, BlockCategory } from '@block-builder/types'

export const BLOCK_DEFINITIONS: BlockDefinition[] = [
  // ─── API ───────────────────────────────────────────────────────────
  { id: 'api-get', category: 'api', label: 'GET Endpoint', description: '查詢資源列表或單筆', icon: 'GET', color: 'api',
    inputs: [{ id: 'input', label: 'Type', type: 'typescript-type' }], outputs: [{ id: 'output', label: 'Endpoint', type: 'api-endpoint' }],
    defaultData: { kind: 'api-endpoint', method: 'GET', path: '/api/resource', summary: 'List resources', auth: false, responseType: 'Resource[]', tags: [] } },
  { id: 'api-post', category: 'api', label: 'POST Endpoint', description: '新增資源', icon: 'POST', color: 'api',
    inputs: [{ id: 'input', label: 'DTO', type: 'typescript-type' }], outputs: [{ id: 'output', label: 'Endpoint', type: 'api-endpoint' }],
    defaultData: { kind: 'api-endpoint', method: 'POST', path: '/api/resource', summary: 'Create resource', auth: false, responseType: 'Resource', bodyType: 'CreateResourceDto', tags: [] } },
  { id: 'api-put', category: 'api', label: 'PUT Endpoint', description: '更新資源', icon: 'PUT', color: 'api',
    inputs: [{ id: 'input', label: 'DTO', type: 'typescript-type' }], outputs: [{ id: 'output', label: 'Endpoint', type: 'api-endpoint' }],
    defaultData: { kind: 'api-endpoint', method: 'PUT', path: '/api/resource/:id', summary: 'Update resource', auth: true, responseType: 'Resource', bodyType: 'UpdateResourceDto', tags: [] } },
  { id: 'api-patch', category: 'api', label: 'PATCH Endpoint', description: '部分更新資源', icon: 'PAT', color: 'api',
    inputs: [], outputs: [{ id: 'output', label: 'Endpoint', type: 'api-endpoint' }],
    defaultData: { kind: 'api-endpoint', method: 'PATCH', path: '/api/resource/:id', summary: 'Patch resource', auth: true, responseType: 'Resource', bodyType: 'PatchResourceDto', tags: [] } },
  { id: 'api-delete', category: 'api', label: 'DELETE Endpoint', description: '刪除資源', icon: 'DEL', color: 'api',
    inputs: [], outputs: [{ id: 'output', label: 'Endpoint', type: 'api-endpoint' }],
    defaultData: { kind: 'api-endpoint', method: 'DELETE', path: '/api/resource/:id', summary: 'Delete resource', auth: true, responseType: 'void', tags: [] } },

  // ─── NestJS ────────────────────────────────────────────────────────
  { id: 'nest-module', category: 'api', label: 'NestJS Module', description: '完整 Module 架構', icon: 'MOD', color: 'api',
    inputs: [], outputs: [{ id: 'output', label: 'Module', type: 'service' }],
    defaultData: { kind: 'nest-module', name: 'ResourceModule', imports: ['TypeOrmModule'], providers: ['ResourceService', 'ResourceRepository'], exports: ['ResourceService'], controllers: ['ResourceController'], global: false } },
  { id: 'nest-service', category: 'api', label: 'NestJS Service', description: '業務邏輯服務層', icon: 'SVC', color: 'api',
    inputs: [{ id: 'input', label: 'Repository', type: 'service' }], outputs: [{ id: 'output', label: 'Service', type: 'service' }],
    defaultData: { kind: 'nest-service', name: 'ResourceService', injectable: true, methods: [{ name: 'findAll', params: '', returnType: 'Promise<Resource[]>', description: 'Get all resources' }, { name: 'findOne', params: 'id: string', returnType: 'Promise<Resource>', description: 'Get one resource' }, { name: 'create', params: 'dto: CreateResourceDto', returnType: 'Promise<Resource>', description: 'Create resource' }, { name: 'update', params: 'id: string, dto: UpdateResourceDto', returnType: 'Promise<Resource>', description: 'Update resource' }, { name: 'remove', params: 'id: string', returnType: 'Promise<void>', description: 'Delete resource' }], dependencies: ['ResourceRepository'] } },
  { id: 'nest-repository', category: 'api', label: 'Repository', description: '資料存取層', icon: 'REP', color: 'api',
    inputs: [{ id: 'input', label: 'Entity', type: 'typescript-type' }], outputs: [{ id: 'output', label: 'Repository', type: 'service' }],
    defaultData: { kind: 'nest-repository', name: 'ResourceRepository', entity: 'Resource', orm: 'prisma', methods: ['findAll', 'findOne', 'create', 'update', 'delete', 'count'] } },

  // ─── Types ─────────────────────────────────────────────────────────
  { id: 'interface', category: 'type', label: 'Interface', description: 'TypeScript interface', icon: 'TS', color: 'type',
    inputs: [], outputs: [{ id: 'output', label: 'Type', type: 'typescript-type' }],
    defaultData: { kind: 'interface', name: 'Resource', fields: [{ name: 'id', type: 'string' }, { name: 'name', type: 'string' }, { name: 'createdAt', type: 'Date', optional: true }] } },
  { id: 'dto', category: 'type', label: 'DTO', description: 'Data Transfer Object + 驗證', icon: 'DTO', color: 'type',
    inputs: [], outputs: [{ id: 'output', label: 'Type', type: 'typescript-type' }],
    defaultData: { kind: 'dto', name: 'CreateResourceDto', fields: [{ name: 'name', type: 'string', validation: ['min(1)'] }], validator: 'zod' } },
  { id: 'enum', category: 'type', label: 'Enum', description: 'TypeScript enum', icon: 'EN', color: 'type',
    inputs: [], outputs: [{ id: 'output', label: 'Type', type: 'typescript-type' }],
    defaultData: { kind: 'enum', name: 'ResourceStatus', values: [{ key: 'ACTIVE', value: 'active' }, { key: 'INACTIVE', value: 'inactive' }, { key: 'PENDING', value: 'pending' }], style: 'string' } },
  { id: 'pagination', category: 'type', label: 'Pagination', description: '分頁型別與邏輯', icon: 'PAG', color: 'type',
    inputs: [], outputs: [{ id: 'output', label: 'Type', type: 'typescript-type' }],
    defaultData: { kind: 'pagination', name: 'ResourcePagination', type: 'offset', defaultLimit: 20, maxLimit: 100, sortable: true } },

  // ─── Logic ─────────────────────────────────────────────────────────
  { id: 'use-query', category: 'logic', label: 'useQuery Hook', description: 'TanStack Query 查詢', icon: 'fn', color: 'logic',
    inputs: [{ id: 'input', label: 'Endpoint', type: 'api-endpoint' }], outputs: [{ id: 'output', label: 'Hook', type: 'hook' }],
    defaultData: { kind: 'use-query', hookName: 'useResourceQuery', endpoint: '/api/resource', responseType: 'Resource[]', staleTime: 300000, retry: 3 } },
  { id: 'use-mutation', category: 'logic', label: 'useMutation Hook', description: 'TanStack Query 變更', icon: 'fn', color: 'logic',
    inputs: [{ id: 'input', label: 'Endpoint', type: 'api-endpoint' }], outputs: [{ id: 'output', label: 'Hook', type: 'hook' }],
    defaultData: { kind: 'use-mutation', hookName: 'useCreateResourceMutation', endpoint: '/api/resource', method: 'POST', bodyType: 'CreateResourceDto', responseType: 'Resource', onSuccessInvalidate: [] } },
  { id: 'store', category: 'logic', label: 'State Store', description: 'Zustand / Pinia 狀態管理', icon: 'ST', color: 'logic',
    inputs: [], outputs: [{ id: 'output', label: 'Store', type: 'hook' }],
    defaultData: { kind: 'store', name: 'useResourceStore', lib: 'zustand', state: [{ name: 'items', type: 'Resource[]' }, { name: 'loading', type: 'boolean' }, { name: 'selected', type: 'Resource | null', optional: true }], actions: [{ name: 'setItems', description: 'Set all items' }, { name: 'setLoading', description: 'Toggle loading state' }, { name: 'selectItem', description: 'Set selected item' }] } },

  // ─── Auth ──────────────────────────────────────────────────────────
  { id: 'auth-guard', category: 'auth', label: 'Auth Guard', description: '路由認證守衛', icon: 'AUTH', color: 'auth',
    inputs: [], outputs: [{ id: 'output', label: 'Guard', type: 'middleware' }],
    defaultData: { kind: 'auth-guard', name: 'JwtAuthGuard', strategy: 'jwt', framework: 'nestjs' } },
  { id: 'jwt', category: 'auth', label: 'JWT Config', description: 'JSON Web Token 設定', icon: 'JWT', color: 'auth',
    inputs: [], outputs: [{ id: 'output', label: 'Auth', type: 'middleware' }],
    defaultData: { kind: 'jwt', name: 'JwtModule', secret: 'process.env.JWT_SECRET', expiresIn: '7d', refreshToken: true, payload: [{ name: 'sub', type: 'string' }, { name: 'email', type: 'string' }, { name: 'role', type: 'string' }] } },
  { id: 'roles', category: 'auth', label: 'Roles Guard', description: '角色權限控制', icon: 'ROLE', color: 'auth',
    inputs: [{ id: 'input', label: 'Guard', type: 'middleware' }], outputs: [{ id: 'output', label: 'Guard', type: 'middleware' }],
    defaultData: { kind: 'roles', name: 'RolesGuard', roles: ['admin', 'user', 'guest'], decorator: 'Roles' } },

  // ─── Infrastructure ────────────────────────────────────────────────
  { id: 'middleware', category: 'infra', label: 'Middleware', description: 'HTTP 中介層', icon: 'MW', color: 'infra',
    inputs: [], outputs: [{ id: 'output', label: 'Middleware', type: 'middleware' }],
    defaultData: { kind: 'middleware', name: 'AppMiddleware', type: 'cors', options: { origin: '*', credentials: 'true' } } },
  { id: 'cache', category: 'infra', label: 'Cache Layer', description: 'Redis / 記憶體快取', icon: 'CACHE', color: 'infra',
    inputs: [], outputs: [{ id: 'output', label: 'Cache', type: 'service' }],
    defaultData: { kind: 'cache', name: 'ResourceCache', store: 'redis', ttl: 300, keyPrefix: 'resource:' } },
  { id: 'file-upload', category: 'infra', label: 'File Upload', description: '檔案上傳元件', icon: 'FILE', color: 'infra',
    inputs: [], outputs: [{ id: 'output', label: 'Component', type: 'react-component' }],
    defaultData: { kind: 'file-upload', componentName: 'FileUploader', accept: ['image/*', '.pdf'], maxSize: 5, multiple: false, storage: 's3', endpoint: '/api/upload' } },
  { id: 'email', category: 'infra', label: 'Email Service', description: '寄送郵件服務', icon: 'MAIL', color: 'infra',
    inputs: [], outputs: [{ id: 'output', label: 'Service', type: 'service' }],
    defaultData: { kind: 'email', name: 'EmailService', provider: 'resend', templates: [{ name: 'welcome', subject: 'Welcome to our platform!' }, { name: 'reset-password', subject: 'Reset your password' }] } },
  { id: 'job', category: 'infra', label: 'Background Job', description: 'Cron / Queue 背景任務', icon: 'JOB', color: 'infra',
    inputs: [], outputs: [{ id: 'output', label: 'Job', type: 'service' }],
    defaultData: { kind: 'job', name: 'CleanupJob', type: 'cron', schedule: '0 2 * * *', lib: 'bullmq' } },
  { id: 'websocket', category: 'infra', label: 'WebSocket', description: '即時雙向通訊', icon: 'WS', color: 'infra',
    inputs: [], outputs: [{ id: 'output', label: 'Gateway', type: 'service' }],
    defaultData: { kind: 'websocket', name: 'ChatGateway', namespace: '/chat', events: [{ name: 'message', payload: 'MessageDto', direction: 'both' }, { name: 'join-room', payload: 'string', direction: 'in' }, { name: 'user-joined', payload: 'string', direction: 'out' }], framework: 'nestjs-gateway' } },

  // ─── UI Components ─────────────────────────────────────────────────
  { id: 'data-table', category: 'ui', label: 'DataTable', description: '可排序分頁表格', icon: 'TBL', color: 'ui',
    inputs: [{ id: 'input', label: 'Hook', type: 'hook' }], outputs: [{ id: 'output', label: 'Component', type: 'react-component' }],
    defaultData: { kind: 'data-table', componentName: 'ResourceTable', dataType: 'Resource', columns: [{ key: 'id', label: 'ID', sortable: false }, { key: 'name', label: 'Name', sortable: true }, { key: 'createdAt', label: 'Created', sortable: true, type: 'date' }], pagination: true, searchable: true } },
  { id: 'form', category: 'ui', label: 'Form', description: 'Zod 驗證表單', icon: 'FRM', color: 'ui',
    inputs: [{ id: 'input', label: 'Hook', type: 'hook' }], outputs: [{ id: 'output', label: 'Component', type: 'react-component' }],
    defaultData: { kind: 'form', componentName: 'CreateResourceForm', dtoType: 'CreateResourceDto', fields: [{ name: 'name', label: 'Name', type: 'text', required: true }], onSubmit: 'useCreateResourceMutation', validator: 'zod' } },
  { id: 'modal', category: 'ui', label: 'Modal', description: '彈窗對話框', icon: 'MDL', color: 'ui',
    inputs: [{ id: 'input', label: 'Component', type: 'react-component' }], outputs: [{ id: 'output', label: 'Component', type: 'react-component' }],
    defaultData: { kind: 'modal', componentName: 'ResourceModal', title: 'Manage Resource', contentComponent: 'CreateResourceForm', actions: [{ label: 'Cancel', variant: 'secondary' }, { label: 'Save', variant: 'primary' }] } },
  { id: 'card', category: 'ui', label: 'Detail Card', description: '資料詳情卡片', icon: 'CRD', color: 'ui',
    inputs: [{ id: 'input', label: 'Hook', type: 'hook' }], outputs: [{ id: 'output', label: 'Component', type: 'react-component' }],
    defaultData: { kind: 'card', componentName: 'ResourceCard', dataType: 'Resource', fields: [{ key: 'name', label: 'Name', type: 'string' }, { key: 'email', label: 'Email', type: 'string' }, { key: 'createdAt', label: 'Created', type: 'date' }], actions: [{ label: 'Edit', variant: 'secondary' }, { label: 'Delete', variant: 'danger' }] } },
  { id: 'chart', category: 'ui', label: 'Chart', description: 'Recharts 資料圖表', icon: 'CHT', color: 'ui',
    inputs: [{ id: 'input', label: 'Hook', type: 'hook' }], outputs: [{ id: 'output', label: 'Component', type: 'react-component' }],
    defaultData: { kind: 'chart', componentName: 'ResourceChart', chartType: 'bar', dataType: 'Resource', xKey: 'name', yKey: 'count', lib: 'recharts' } },
  { id: 'search-bar', category: 'ui', label: 'Search Bar', description: '即時搜尋元件', icon: 'SCH', color: 'ui',
    inputs: [], outputs: [{ id: 'output', label: 'Component', type: 'react-component' }],
    defaultData: { kind: 'search-bar', componentName: 'ResourceSearch', placeholder: 'Search resources...', searchType: 'remote', endpoint: '/api/resource/search', debounce: 300, resultType: 'Resource' } },
  { id: 'notification', category: 'ui', label: 'Notifications', description: 'Toast 通知系統', icon: 'NTF', color: 'ui',
    inputs: [], outputs: [{ id: 'output', label: 'Component', type: 'react-component' }],
    defaultData: { kind: 'notification', componentName: 'Toaster', lib: 'sonner', position: 'top-right', types: ['success', 'error', 'warning', 'info'] } },

  // ─── Layout ────────────────────────────────────────────────────────
  { id: 'navigation', category: 'layout', label: 'Navigation', description: 'Navbar / Sidebar / Tabs', icon: 'NAV', color: 'layout',
    inputs: [], outputs: [{ id: 'output', label: 'Component', type: 'react-component' }],
    defaultData: { kind: 'navigation', componentName: 'AppNavbar', type: 'navbar', items: [{ label: 'Dashboard', path: '/' }, { label: 'Users', path: '/users' }, { label: 'Settings', path: '/settings' }], auth: true } },
  { id: 'file-upload-ui', category: 'layout', label: 'File Upload UI', description: '拖放上傳介面', icon: 'UPL', color: 'layout',
    inputs: [{ id: 'input', label: 'Service', type: 'service' }], outputs: [{ id: 'output', label: 'Component', type: 'react-component' }],
    defaultData: { kind: 'file-upload', componentName: 'DropzoneUploader', accept: ['image/*'], maxSize: 10, multiple: true, storage: 's3', endpoint: '/api/upload' } },

  // ─── New blocks ────────────────────────────────────────────────────
  { id: 'page', category: 'layout', label: 'Page Route', description: 'React Router 頁面路由', icon: 'PG', color: 'layout',
    inputs: [{ id: 'input', label: 'Component', type: 'react-component' }], outputs: [{ id: 'output', label: 'Page', type: 'react-component' }],
    defaultData: { kind: 'page', name: 'HomePage', path: '/', title: 'Home', protected: false, layout: 'default' } },
  { id: 'oauth', category: 'auth', label: 'OAuth 登入', description: 'Google/GitHub/Discord OAuth', icon: 'OAUTH', color: 'auth',
    inputs: [], outputs: [{ id: 'output', label: 'Auth', type: 'middleware' }],
    defaultData: { kind: 'oauth', name: 'OAuthProvider', providers: ['google', 'github'], callbackPath: '/auth/callback', successRedirect: '/dashboard' } },
  { id: 'stripe', category: 'infra', label: 'Stripe 支付', description: 'Stripe Checkout 整合', icon: 'PAY', color: 'infra',
    inputs: [], outputs: [{ id: 'output', label: 'Service', type: 'service' }],
    defaultData: { kind: 'stripe', name: 'StripeService', products: [{ name: 'Pro Plan', priceId: 'price_xxx', amount: 999, currency: 'usd' }], successUrl: '/success', cancelUrl: '/cancel', webhookEndpoint: '/api/webhooks/stripe' } },
  { id: 'infinite-scroll', category: 'logic', label: 'Infinite Scroll', description: 'useInfiniteQuery 無限捲動', icon: 'INF', color: 'logic',
    inputs: [{ id: 'input', label: 'Endpoint', type: 'api-endpoint' }], outputs: [{ id: 'output', label: 'Hook', type: 'hook' }],
    defaultData: { kind: 'infinite-scroll', hookName: 'useInfiniteResources', endpoint: '/api/resources', responseType: 'Resource[]', cursorField: 'cursor', pageSize: 20 } },
]

export const BLOCK_DEF_MAP = Object.fromEntries(BLOCK_DEFINITIONS.map((b) => [b.id, b]))

export const CATEGORIES: { id: BlockCategory; label: string; color: string }[] = [
  { id: 'api', label: 'API & NestJS', color: 'api' },
  { id: 'type', label: 'TypeScript 型別', color: 'type' },
  { id: 'logic', label: 'React Hooks & Store', color: 'logic' },
  { id: 'auth', label: '認證與授權', color: 'auth' },
  { id: 'infra', label: '基礎設施', color: 'infra' },
  { id: 'ui', label: 'UI 組件', color: 'ui' },
  { id: 'layout', label: '版面配置', color: 'layout' },
]
